Adapt to t8code (#63)
adapt
* julia install script
* docs
* github workflow

diff --git a/utils/libtrixi-init-julia b/utils/libtrixi-init-julia
--- a/utils/libtrixi-init-julia
+++ b/utils/libtrixi-init-julia
@@ -6,8 +6,9 @@ usage: libtrixi-init-julia [-h] [-f]
                            [--julia-depot JULIA_DEPOT]
                            [--julia-exec JULIA_EXEC]
                            [--mpi-library MPI_LIBRARY]
+                           [--t8code-library T8CODE_LIBRARY]
                            [--p4est-library P4EST_LIBRARY]
-                           [--sc-library P4EST_LIBRARY]
+                           [--sc-library SC_LIBRARY]
                            PREFIX_OR_REPO
 
 Set up all necessary project files in the current working directory and set appropriate
@@ -55,15 +56,22 @@ optional arguments:
                     'path/to/libmpi.so'. If empty, Julia will try to figure out the path
                     automatically. (default: '')
 
+    --t8code-library T8CODE_LIBRARY
+                    Path to the t8code shared library, i.e., something like
+                    'path/to/libt8.so'. If empty, Julia will try to figure out the path
+                    automatically. (default: '')
+
     --p4est-library P4EST_LIBRARY
                     Path to the p4est shared library, i.e., something like
-                    'path/to/libp4est.so'. If empty, Julia will try to figure out the path
-                    automatically. (default: '')
+                    'path/to/libp4est.so'.  If omitted, it will be assumed to be located
+                    next to the t8code library. (default: '\$(dirname \$T8CODE_LIBRARY)/
+                    libp4est.so')
 
     --sc-library SC_LIBRARY
                     Path to the sc shared library, i.e., something like
                     'path/to/libsc.so'. If omitted, it will be assumed to be located next
-                    to the p4est library. (default: '\$(dirname \$P4EST_LIBRARY)/libsc.so')
+                    to the t8code library. (default: '\$(dirname \$T8CODE_LIBRARY)/
+                    libsc.so')
 EOF
 }
 
@@ -111,6 +119,10 @@ while [[ $# -gt 0 ]]; do
       ;;
     --mpi-library)
       LIBTRIXI_MPI_LIBRARY="$2"
+      shift 2
+      ;;
+    --t8code-library)
+      LIBTRIXI_T8CODE_LIBRARY="$2"
       shift 2
       ;;
     --p4est-library)
@@ -180,12 +192,24 @@ if [ ! -f "$mpi_library" ]; then
   die "MPI library '$mpi_library' not found" 2
 fi
 
-# Check if libpest.so was given by the user or try to find it using Julia
-if [ -z "$LIBTRIXI_P4EST_LIBRARY" ]; then
-  p4est_libdir="$($julia_exec -e 'using Libdl; find_library("libp4est") |> dlpath |> dirname |> println')"
-  if [ -z "$p4est_libdir" ]; then
-    die "location of p4est library could not be determined automatically (use '--p4est-library' instead)"
+# Check if libt8.so was given by the user or try to find it using Julia
+if [ -z "$LIBTRIXI_T8CODE_LIBRARY" ]; then
+  t8code_libdir="$($julia_exec -e 'using Libdl; find_library("libt8") |> dlpath |> dirname |> println')"
+  if [ -z "$t8code_libdir" ]; then
+    die "location of t8code library could not be determined automatically (use '--t8code-library' instead)"
   fi
+else
+  t8code_libdir="$(dirname $LIBTRIXI_T8CODE_LIBRARY)"
+fi
+t8code_libdir_abs="$(cd $t8code_libdir && pwd)"
+t8code_library="$t8code_libdir_abs/libt8.so"
+if [ ! -f "$t8code_library" ]; then
+  die "t8code library '$t8code_library' not found" 2
+fi
+
+# Check if libp4est.so was given by the user or else assume it is next to libt8.so
+if [ -z "$LIBTRIXI_P4EST_LIBRARY" ]; then
+  p4est_libdir="$t8code_libdir"
 else
   p4est_libdir="$(dirname $LIBTRIXI_P4EST_LIBRARY)"
 fi
@@ -195,9 +219,9 @@ if [ ! -f "$p4est_library" ]; then
   die "p4est library '$p4est_library' not found" 2
 fi
 
-# Check if libsc.so was given by the user or else assume it is next to libp4est.so
+# Check if libsc.so was given by the user or else assume it is next to libt8.so
 if [ -z "$LIBTRIXI_SC_LIBRARY" ]; then
-  sc_libdir="$p4est_libdir"
+  sc_libdir="$t8code_libdir"
 else
   sc_libdir="$(dirname $LIBTRIXI_SC_LIBRARY)"
 fi
@@ -236,9 +260,8 @@ JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
     $julia_exec --project=. \
     -e "
 using Pkg
-Pkg.add([\"Preferences\", \"UUIDs\", \"MPIPreferences\", \"P4est\", \"HDF5\", \
-         \"MPI\"])
-"
+Pkg.add([\"Preferences\", \"UUIDs\", \"MPIPreferences\", \"T8code\", \
+         \"P4est\", \"HDF5\", \"MPI\"])"
 [ $? -eq 0 ] || die "could not install dependencies"
 echo
 
@@ -252,6 +275,20 @@ MPIPreferences.use_system_binary(; library_names=\"$mpi_library\")
 [ $? -eq 0 ] || die "could not configure system MPI library for Julia"
 echo
 
+# Set system t8code library
+echo "Use system t8code for Julia... "
+JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. \
+    -e "
+using Preferences, UUIDs
+set_preferences!(UUID(\"d0cc0030-9a40-4274-8435-baadcfd54fa1\"),
+                 \"libt8\" => \"$t8code_library\",
+                 \"libp4est\" => \"$p4est_library\",
+                 \"libsc\" => \"$sc_library\",
+                 force = true)
+"
+[ $? -eq 0 ] || die "could not configure system t8code library for Julia"
+echo
+
 # Set system p4est library
 echo "Use system p4est for Julia... "
 JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. \
@@ -259,7 +296,7 @@ JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. \
 using Preferences, UUIDs
 set_preferences!(UUID(\"7d669430-f675-4ae7-b43e-fab78ec5a902\"),
                  \"libp4est\" => \"$p4est_library\",
-                 \"libpsc\" => \"$sc_library\",
+                 \"libsc\" => \"$sc_library\",
                  force = true)
 "
 [ $? -eq 0 ] || die "could not configure system p4est library for Julia"
