Speed up CI testing by precompiling only once (#95)
* Add CI badge to README

* Add `--skip-precompile` option

* Rearrange CI testing to hopefully precompile Julia packages only once

* Use `--check-bounds=auto` for tests in the hope of avoiding double precompilation

* Do not skip precompilation

* Reverse order again

* Re-order yet again

* Update rationale for `--skip-precompile`

diff --git a/utils/libtrixi-init-julia b/utils/libtrixi-init-julia
--- a/utils/libtrixi-init-julia
+++ b/utils/libtrixi-init-julia
@@ -9,6 +9,7 @@ usage: libtrixi-init-julia [-h] [-f]
                            [--t8code-library T8CODE_LIBRARY]
                            [--p4est-library P4EST_LIBRARY]
                            [--sc-library SC_LIBRARY]
+                           [--skip-precompile]
                            PREFIX_OR_REPO
 
 Set up all necessary project files in the current working directory and set appropriate
@@ -38,6 +39,10 @@ optional arguments:
     --force, -f     By default, this tool does nothing if any of the files/folders to be
                     created already exist. With this option given on the command line, it
                     will continue anyways.
+
+    --skip-precompile
+                    Do not precompile Julia packages. This can be helpful, e.g., when
+                    planning to add more packages manually.
 
     --julia-depot JULIA_DEPOT
                     Path to the Julia depot to be used, i.e., the folder where all Julia
@@ -87,6 +92,7 @@ die() {
 # Parse arguments (based on https://stackoverflow.com/a/14203146/1329844)
 POSITIONAL_ARGS=()
 USE_FORCE=0
+SKIP_PRECOMPILE=0
 if [ -z "$LIBTRIXI_JULIA_EXEC" ]; then
   LIBTRIXI_JULIA_EXEC=julia
 fi
@@ -103,6 +109,10 @@ while [[ $# -gt 0 ]]; do
       ;;
     -f|--force)
       USE_FORCE=1
+      shift
+      ;;
+    --skip-precompile)
+      SKIP_PRECOMPILE=1
       shift
       ;;
     --julia-exec)
@@ -338,12 +348,14 @@ Pkg.add([\"Trixi\", \"OrdinaryDiffEq\"])
 echo
 
 # Install and precompile everything
-echo "Precompile all packages ..."
-JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
-    $julia_exec --project=. \
-    -e "using Pkg; Pkg.precompile(strict=true)"
-[ $? -eq 0 ] || die "could not precompile packages"
-echo
+if [ $SKIP_PRECOMPILE -ne 1 ]; then
+  echo "Precompile all packages ..."
+  JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
+      $julia_exec --project=. \
+      -e "using Pkg; Pkg.precompile(strict=true)"
+  [ $? -eq 0 ] || die "could not precompile packages"
+  echo
+fi
 
 
 # Congratulate user
