Do not use heredocs since they prevent proper error code propagation

diff --git a/utils/libtrixi-init-julia b/utils/libtrixi-init-julia
--- a/utils/libtrixi-init-julia
+++ b/utils/libtrixi-init-julia
@@ -3,9 +3,11 @@
 usage() {
   cat << EOF >&2
 usage: libtrixi-init-julia [-h] [-f]
+                           [--julia-depot JULIA_DEPOT]
                            [--julia-exec JULIA_EXEC]
                            [--mpi-library MPI_LIBRARY]
                            [--p4est-library P4EST_LIBRARY]
+                           [--sc-library P4EST_LIBRARY]
                            PREFIX_OR_REPO
 
 Set up all necessary project files in the current working directory and set appropriate
@@ -36,12 +38,12 @@ optional arguments:
                     created already exist. With this option given on the command line, it
                     will continue anyways.
 
-    --julia-exec JULIA_EXEC
-                    Path to Julia executable. (default: 'julia')
-
     --julia-depot JULIA_DEPOT
                     Path to the Julia depot to be used, i.e., the folder where all Julia
                     packages, Julia cache files etc. are stored. (default: 'julia-depot')
+
+    --julia-exec JULIA_EXEC
+                    Path to Julia executable. (default: 'julia')
 
     --mpi-library MPI_LIBRARY
                     Path to the MPI C shared library, i.e., something like
@@ -102,6 +104,10 @@ while [[ $# -gt 0 ]]; do
       ;;
     --p4est-library)
       LIBTRIXI_P4EST_LIBRARY="$2"
+      shift 2
+      ;;
+    --sc-library)
+      LIBTRIXI_SC_LIBRARY="$2"
       shift 2
       ;;
     -*|--*)
@@ -188,6 +194,14 @@ if [ $USE_FORCE -ne 1 ]; then
   done
 fi
 
+# Install dependencies for configuration
+echo "Install dependencies for configuration..."
+JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
+    $julia_exec --project=. \
+    -e "using Pkg; Pkg.add([\"Preferences\", \"UUIDs\", \"MPIPreferences\", \"P4est\"])"
+[ $? -eq 0 ] || die "could not install dependencies"
+echo
+
 # Develop LibTrixi.jl
 echo "Install LibTrixi.jl..."
 JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
@@ -198,33 +212,24 @@ echo
 
 # Set system MPI library
 echo "Use system MPI for Julia... "
-JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. << EOF
-# Install MPIPreferences
-using Pkg
-Pkg.add("MPIPreferences")
-
-# Configure Julia to use system MPI library
+JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. \
+    -e "
 using MPIPreferences
-MPIPreferences.use_system_binary(; library_names="$mpi_library")
-EOF
+MPIPreferences.use_system_binary(; library_names=\"$mpi_library\")
+"
 [ $? -eq 0 ] || die "could not configure system MPI library for Julia"
 echo
 
 # Set system p4est library
 echo "Use system p4est for Julia... "
-JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. << EOF
-# Install dependencies
-using Pkg
-Pkg.add(["Preferences", "UUIDs", "P4est"])
-
-# Configure Julia to use system p4est library
+JULIA_DEPOT_PATH="$julia_depot" $julia_exec --project=. \
+    -e "
 using Preferences, UUIDs
-
-set_preferences!(UUID("7d669430-f675-4ae7-b43e-fab78ec5a902"),
-                 "libp4est" => "$p4est_library", force = true);
-set_preferences!(UUID("7d669430-f675-4ae7-b43e-fab78ec5a902"),
-                 "libpsc" => "$sc_library", force = true)
-EOF
+set_preferences!(UUID(\"7d669430-f675-4ae7-b43e-fab78ec5a902\"),
+                 \"libp4est\" => \"$p4est_library\", force = true);
+set_preferences!(UUID(\"7d669430-f675-4ae7-b43e-fab78ec5a902\"),
+                 \"libpsc\" => \"$sc_library\", force = true)
+"
 [ $? -eq 0 ] || die "could not configure system p4est library for Julia"
 echo
 
