Add Trixi.jl and OrdinaryDiffEq.jl (#20)
* C and Fortran controller examples

* Real Trixi examples

* Docs

diff --git a/utils/libtrixi-init-julia b/utils/libtrixi-init-julia
--- a/utils/libtrixi-init-julia
+++ b/utils/libtrixi-init-julia
@@ -187,17 +187,20 @@ if [ -z "$LIBTRIXI_P4EST_LIBRARY" ]; then
 else
   p4est_libdir="$(dirname $LIBTRIXI_P4EST_LIBRARY)"
 fi
-p4est_library="$p4est_libdir/libp4est.so"
+p4est_libdir_abs="$(cd $p4est_libdir && pwd)"
+p4est_library="$p4est_libdir_abs/libp4est.so"
 if [ ! -f "$p4est_library" ]; then
   die "p4est library '$p4est_library' not found" 2
 fi
 
 # Check if libsc.so was given by the user or else assume it is next to libp4est.so
 if [ -z "$LIBTRIXI_SC_LIBRARY" ]; then
-  sc_library="$p4est_libdir/libsc.so"
+  sc_libdir="$p4est_libdir"
 else
-  sc_library="$LIBTRIXI_SC_LIBRARY"
+  sc_libdir="$(dirname $LIBTRIXI_SC_LIBRARY)"
 fi
+sc_libdir_abs="$(cd $sc_libdir && pwd)"
+sc_library="$sc_libdir_abs/libsc.so"
 if [ ! -f "$sc_library" ]; then
   die "sc library '$sc_library' not found" 2
 fi
@@ -234,14 +237,6 @@ using Pkg
 Pkg.add([\"Preferences\", \"UUIDs\", \"MPIPreferences\", \"P4est\", \"HDF5\"])
 "
 [ $? -eq 0 ] || die "could not install dependencies"
-echo
-
-# Develop LibTrixi.jl
-echo "Install LibTrixi.jl..."
-JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
-    $julia_exec --project=. \
-    -e "using Pkg; Pkg.develop(path=\"$libtrixi_jl_path\")"
-[ $? -eq 0 ] || die "could not install LibTrixi.jl"
 echo
 
 # Set system MPI library
@@ -281,6 +276,25 @@ JULIA_HDF5_PATH="$hdf5_libdir" JULIA_DEPOT_PATH="$julia_depot" $julia_exec --pro
 #                  force = true)
 # "
 [ $? -eq 0 ] || die "could not configure system HDF5 library for Julia"
+echo
+
+# Develop LibTrixi.jl
+echo "Install LibTrixi.jl..."
+JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
+    $julia_exec --project=. \
+    -e "using Pkg; Pkg.develop(path=\"$libtrixi_jl_path\")"
+[ $? -eq 0 ] || die "could not install LibTrixi.jl"
+echo
+
+# Install remaining dependencies
+echo "Install Trixi.jl and OrdinaryDiffEq.jl..."
+JULIA_DEPOT_PATH="$julia_depot" JULIA_PKG_PRECOMPILE_AUTO=0 \
+    $julia_exec --project=. \
+    -e "
+using Pkg
+Pkg.add([\"Trixi\", \"OrdinaryDiffEq\"])
+"
+[ $? -eq 0 ] || die "could not install dependencies"
 echo
 
 # Install and precompile everything
