C API test using google test (#80)
* add a google test test

* use cmake to setup google test and tests

* add option to compile for coverage analysis

* adapt github workflow to use ctest

* install gtest

* one "extern" is enough

* googletest contains sources only...

* adapt to API change trixi_version_library_*

* add test of trixi_eval_julia

somehow caputring of stdout / stderr does not work here

* testing assembly of function pointers

* add tests for auxiliary functions

* add test for too long project path

* create a cmake taget for creating coverage report

* install gcovr

* check the return value of realpath

* modify to not get caught by realpath error

* revert cmake coverage feature

* fix CI

* debug CI

* /tmp not accessible?

* fake depot folder

* incorrect calls of examples to cover error handling

* try to check return code

* will this return 2 as exit code?

* Update src/auxiliary.c

Co-authored-by: Michael Schlottke-Lakemper <michael@sloede.com>

* suggestions from review

---------

Co-authored-by: Michael Schlottke-Lakemper <michael@sloede.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,6 +85,9 @@ jobs:
       - name: Install HDF5
         run: |
           sudo apt-get install -y libhdf5-openmpi-dev
+      - name: Install gtest
+        run: |
+          sudo apt-get install -y libgtest-dev
       - name: Install t8code
         run: |
           T8CODE_RELEASE=1.4.1
@@ -110,10 +113,12 @@ jobs:
           mkdir build
           cd build
           cmake .. -DCMAKE_INSTALL_PREFIX=../install \
+                   -DCMAKE_BUILD_TYPE=Debug \
                    -DCMAKE_C_FLAGS="-cpp --coverage -O0" \
                    -DCMAKE_Fortran_FLAGS="-cpp --coverage -O0" \
                    -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
-                   -DCMAKE_SHARED_LINKER_FLAGS="--coverage"
+                   -DCMAKE_SHARED_LINKER_FLAGS="--coverage" \
+                   -DENABLE_TESTING=ON -DJULIA_PROJECT_PATH=../libtrixi-julia
       - name: Build
         run: |
           cd build
@@ -131,9 +136,12 @@ jobs:
         # Note that we set the Julia depot to `~/.julia` *ONLY* to make use of the
         # julia-actions/cache above (which unfortunately hardcoded the `~/.julia`
         # directory). For this reason, we also need to use `--force`
+        # Still create subfolder `julia-depot`, which reflects the typical default
+        # and is tested below
         run: |
           mkdir libtrixi-julia
           cd libtrixi-julia
+          mkdir julia-depot
           ../install/bin/libtrixi-init-julia .. \
               --hdf5-library /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so \
               --t8code-library ../t8code-local/prefix/lib/libt8.so \
@@ -165,6 +173,37 @@ jobs:
               ../build/examples/trixi_controller_data_f . libelixir_p4est2d_dgsem_euler_sedov.jl
         env:
           LIBTRIXI_DEBUG: all
+      - name: Check error handling of examples
+        if: ${{ matrix.test_type == 'coverage' }}
+        run: |
+          cd libtrixi-julia
+          set +e  # disable early exit on non-zero exit code
+          for command in "../build/examples/simple_trixi_controller_c" \
+                         "../build/examples/simple_trixi_controller_c ." \
+                         "../build/examples/simple_trixi_controller_f" \
+                         "../build/examples/simple_trixi_controller_f ." \
+                         "../build/examples/trixi_controller_data_c" \
+                         "../build/examples/trixi_controller_data_c ." \
+                         "../build/examples/trixi_controller_data_f" \
+                         "../build/examples/trixi_controller_data_f ."
+            do
+              $command
+              if [ $? -ne 2 ]; then
+                echo "Wrong exit code for $command! Expected 2, got $?"
+                exit 1
+              fi
+            done
+        env:
+          LIBTRIXI_DEBUG: all
+          JULIA_DEPOT_PATH: ~/.julia
+      - name: Run CTest/gtest tests
+        if: ${{ matrix.test_type == 'coverage' }}
+        run: |
+          cd build/test
+          ctest -V
+        env:
+          LIBTRIXI_DEBUG: all
+          JULIA_DEPOT_PATH: ~/.julia
       - name: Run memory checks with Valgrind
         if: ${{ matrix.test_type == 'valgrind' }}
         run: |
