try to check return code

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -175,17 +175,24 @@ jobs:
           LIBTRIXI_DEBUG: all
       - name: Check error handling of examples
         if: ${{ matrix.test_type == 'coverage' }}
-        continue-on-error: true
         run: |
           cd libtrixi-julia
-          ../build/examples/simple_trixi_controller_c
-          ../build/examples/simple_trixi_controller_c .
-          ../build/examples/simple_trixi_controller_f
-          ../build/examples/simple_trixi_controller_f .
-          ../build/examples/trixi_controller_data_c
-          ../build/examples/trixi_controller_data_c .
-          ../build/examples/trixi_controller_data_f
-          ../build/examples/trixi_controller_data_f .
+          set +e  # disable early exit on non-zero exit code
+          for command in "../build/examples/simple_trixi_controller_c" \
+                         "../build/examples/simple_trixi_controller_c ." \
+                         "../build/examples/simple_trixi_controller_f" \
+                         "../build/examples/simple_trixi_controller_f ." \
+                         "../build/examples/trixi_controller_data_c" \
+                         "../build/examples/trixi_controller_data_c ." \
+                         "../build/examples/trixi_controller_data_f" \
+                         "../build/examples/trixi_controller_data_f ."
+            do
+              $command
+              if [ $? -ne 2 ]; then
+                echo "Wrong exit code for $command! Expected 2, got $?"
+                exit 1
+              fi
+            done
         env:
           LIBTRIXI_DEBUG: all
           JULIA_DEPOT_PATH: ~/.julia
